### PR TITLE
Update glovo fork of AWS Wrangler

### PR DESCRIPTION
**Pull request by RafaAguilar**
- Adds redshift map credentials support
- Poetry Support

### CODE REVIEW

**Comment by razvantudorica-gl** [comment]
Hi
Where do we plan to use  AWS Wrangler?

**Comment by RafaAguilar** [comment]
It is coming from a CDS requirement @razvantudorica-gl  https://glovoapp.atlassian.net/browse/CDS-221 

They are adding it to corelib. Form more info Adria y Chris Collins

**Comment by RafaAguilar** [comment]
Check also this PR: https://github.com/Glovo/machine-learning-platform/pull/2750

**Comment by razvantudorica-gl** [comment]
Nice! Thx. 
Do you think that it makes sense to do a PR back to the original repo?

**Pull request merged**
